/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../views/AboutView.vue')['default']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    CarbonClose: typeof import('./../components/icon/CarbonClose.vue')['default']
    CarbonMoon: typeof import('./../components/icon/CarbonMoon.vue')['default']
    CarbonSettings: typeof import('./../components/icon/CarbonSettings.vue')['default']
    ContactUs: typeof import('./../views/ContactUs.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Home: typeof import('./../views/Home.vue')['default']
    HomeView: typeof import('./../views/HomeView.vue')['default']
    IcBaselineWbSunny: typeof import('./../components/icon/IcBaselineWbSunny.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconFont: typeof import('./../components/icon/iconFont.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    IntellectualProperty: typeof import('./../views/IntellectualProperty.vue')['default']
    LangIcon: typeof import('./../components/icon/LangIcon.vue')['default']
    Layout: typeof import('./../layout/Layout.vue')['default']
    LogosBitriseIcon: typeof import('./../components/icon/LogosBitriseIcon.vue')['default']
    Members: typeof import('./../views/Members.vue')['default']
    ResearchArea: typeof import('./../views/ResearchArea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialMedia: typeof import('./../views/SocialMedia.vue')['default']
    SvgIcon: typeof import('./../components/icon/svgIcon.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    ToggleLanguage: typeof import('./../components/ToggleLanguage.vue')['default']
    TopHead: typeof import('./../components/layout/TopHead.vue')['default']
    Welcome: typeof import('./../components/Welcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
